# Architecture identifier.
arch = "aarch64"
# Platform identifier.
platform = "aarch64-raspi3b"
# Platform family.
family = "aarch64-raspi"

# Base address of the whole physical memory.
phys-memory-base = "0x0"
# Size of the whole physical memory.
phys-memory-size = "0x3EFF_FFFF"     # 0.98G
# Base physical address of the kernel image.
kernel-base-paddr = "0x8_0000"
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_0000_0008_0000"
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_0000_0000_0000"
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    ["0x3F20_0000", "0x1000"], # GPIO
    ["0x3F20_1000", "0x1000"], # PL011 UART
]
virtio-mmio-regions = []

# GPIO Address
gpio-paddr = "0x3F20_0000"
# UART Address
uart-paddr = "0x3F20_1000"
uart-irq = "0x39"

